### ISSUE TITLE
Feature request: Python string values

### ISSUE THREAD

**Issue by cortesi** [bw2/ConfigArgParse#10]
I'm just about to release the first version of [mitmproxy](http://github.com/mitmproxy/mitmproxy) with config parsing based on ConfigArgParse. Thanks a bunch for your solid work. 

Something we'd find immensely useful is the ability to specify values in key/value pairs as Python strings and triple-quoted multi-line strings, with Python-style escape sequences. This would make the config files for our tools hugely more powerful.

This would require converting the current parser to something more sophisticated. [PyParsing](http://pyparsing.wikispaces.com/) has built-in definitions for quoted strings, and implementing the parser in it would not be very much work.

I don't have the bandwidth for this myself, but please let me know if a patch like this would be pulled, and I may get to it some time down the track.

**Comment by bw2** [comment]
coalesced into #30
