### ISSUE TITLE
Wrong parsing for empty strings

### ISSUE THREAD

**Issue by jerinphilip** [bw2/ConfigArgParse#103]
I'm trying to use this library on [OpenNMT-py/opts.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/opts.py), please find a [sample-train-config](https://ptpb.pw/3yAu).

I get the following error, while trying to work with the above config file.
```
train.py: error: argument -decay_method/--decay_method: invalid choice: '=' (choose from 'noam')
```

I want to enforce the behaviour that this is read as an empty string. I believe this issue is to be solved at your end, than the config file. Could you guide me to where I should be looking to fix this?

**Comment by bw2** [comment]
It looks like this library is using plain argparse, so assuming this issue no longer applies?

**Comment by bw2** [comment]
This is a bug in the default parser. 
If you're ok with using YAML syntax, you could switch to 
`config_file_parser_class=YAMLConfigFileParser` .

**Comment by macfreek** [comment]
The current regular expression in [the `parse()` method](https://github.com/bw2/ConfigArgParse/blob/2c743df7ae708a7ae1f282f9e68c15621c53b75c/configargparse.py#L154) is not so great in my opinion.

It currently is:

    m=re.match(r'^(?P<key>[^:=;#\s]+?)\s*[:=\s]\s*(?P<value>.+?)\s*(?P<comment>\s[;#].*)?$', line)

A better regular expression is:

    m=re.match(r'^\s*(?P<key>\w+?)\s*[:=\s]\s*(?P<value>.+?)?\s*(?P<comment>\s[;#].*)?$', line)

Here is the class I use in my code:

    class ConfigFileParser(configargparse.DefaultConfigFileParser):
        def parse(self, stream):
            """Parses the keys + values from a config file."""
            # Workaround for https://github.com/bw2/ConfigArgParse/issues/103
            items = OrderedDict()
            for i, line in enumerate(stream):
                line = line.strip()
                if not line or line[0] in ["#", ";", "["] or line.startswith("---"):
                    continue
                
                match = re.match(r'^(?P<key>\w+)\s*' 
                                 r'(?:(?P<equal>[:=\s])\s*([\'"]?)(?P<value>.+?)?\3)?'
                                 r'\s*(?:\s[;#]\s*(?P<comment>.*?)\s*)?$', line)
                if not match:
                    raise ConfigFileParserException("Unexpected line %s in %s: %s" % 
                            (i, getattr(stream, 'name', 'stream'), line))
                
                key = match.group('key')
                equal = match.group('equal')
                value = match.group('value')
                comment = match.group('comment')
                if value is None and equal is not None and equal is not ' ':
                    # distinguish "key = " (value = '')
                    # from simply "key" (value = None)
                    value = ''
                
                if value is None:  # key-only
                    value = 'true'
                elif value.startswith("[") and value.endswith("]"):
                    value = [elem.strip() for elem in value[1:-1].split(",")]
                
                items[key] = value
            return items

This has a few advantages over the regular class:

| Input           | configargparse Value | Value in above code     |
|-----------------|---------------|---------------|
| key =           | =             |               |
| key=            | N/A (error)   |               |
| key             | None ('true') | None ('true') |
| key = '#'       | '#'           | #             |
| key = :         | :             | :             |
| key : =         | =             | =             |
| key = =         | =             | =             |
| key = ' '       | ' '           |       (space) |
| key = '''       | '''           | '             |
| key = "'"       | "'"           | '             |

For those interested, below is the full test code of this regexp:

    import re
    
    def current_parse(line):
        line = line.strip()
        white_space = r"\s*"
        key = r"(?P<key>[^:=;#\s]+?)"
        value = white_space+"[:=\s]"+white_space+"(?P<value>.+?)"
        comment = white_space+r"(?P<comment>\s[;#].*)?"
    
        key_only_match = re.match("^" + key + comment + "$", line)
        if key_only_match:
            key = key_only_match.group("key")
            comment = key_only_match.group("comment")
            if comment:
                comment = comment.strip()[1:].strip()
            return key, None, comment
        key_value_match = re.match("^"+key+value+comment+"$", line)
        if key_value_match:
            key = key_value_match.group("key")
            value = key_value_match.group("value")
            comment = key_value_match.group("comment")
            if value and value[0] == value[-1] and len(value) > 2and value[0] in '\'"':
                value = value[1:-1]
            if comment:
                comment = comment.strip()[1:].strip()
            return key, value, comment
        return None, None, None
    
    
    def quote_parse(line):
        m=re.match(r'^\s*(?P<key>\w+?)\s*'
                   r'(?:(?P<equal>[:=\s])\s*([\'"]?)(?P<value>.+?)?\3)?'
                   r'\s*(?:\s[;#]\s*(?P<comment>.*?)\s*)?$', line)
        key = m.group('key')
        equal = m.group('equal')
        value = m.group('value')
        comment = m.group('comment')
        if value is None and equal is not None and equal is not ' ':
            value = ''
        return key, value, comment
    
    
    def test_parser(func, line, expected_key, expected_value, expected_comment):
        actual_key, actual_value, actual_comment = func(line)
        if actual_key != expected_key or actual_value != expected_value or actual_comment != expected_comment:
            print("Error in %s(%r)" % (func.__name__, line))
            print("   Expected %r  %r  %r" % (expected_key, expected_value, expected_comment))
            print("   Received %r  %r  %r" % (actual_key, actual_value, actual_comment))
    
    parser = current_parse
    # parser = quote_parse
    
    test_parser(parser, 'key=value',                         'key', 'value', None)
    test_parser(parser, 'key =value',                        'key', 'value', None)
    test_parser(parser, 'key= value',                        'key', 'value', None)
    test_parser(parser, 'key = value',                       'key', 'value', None)
    test_parser(parser, 'key  =  value',                     'key', 'value', None)
    test_parser(parser, ' key  =  value ',                   'key', 'value', None)
    test_parser(parser, 'key:value',                         'key', 'value', None)
    test_parser(parser, 'key :value',                        'key', 'value', None)
    test_parser(parser, 'key: value',                        'key', 'value', None)
    test_parser(parser, 'key : value',                       'key', 'value', None)
    test_parser(parser, 'key  :  value',                     'key', 'value', None)
    test_parser(parser, ' key  :  value ',                   'key', 'value', None)
    test_parser(parser, 'key value',                         'key', 'value', None)
    test_parser(parser, 'key  value',                        'key', 'value', None)
    test_parser(parser, ' key    value ',                    'key', 'value', None)
    test_parser(parser, 'key=',                              'key', '', None)
    test_parser(parser, 'key =',                             'key', '', None)
    test_parser(parser, 'key= ',                             'key', '', None)
    test_parser(parser, 'key = ',                            'key', '', None)
    test_parser(parser, 'key  =  ',                          'key', '', None)
    test_parser(parser, ' key  =   ',                        'key', '', None)
    test_parser(parser, 'key:',                              'key', '', None)
    test_parser(parser, 'key :',                             'key', '', None)
    test_parser(parser, 'key: ',                             'key', '', None)
    test_parser(parser, 'key : ',                            'key', '', None)
    test_parser(parser, 'key  :  ',                          'key', '', None)
    test_parser(parser, ' key  :   ',                        'key', '', None)
    test_parser(parser, 'key=:',                             'key', ':', None)
    test_parser(parser, 'key =:',                            'key', ':', None)
    test_parser(parser, 'key= :',                            'key', ':', None)
    test_parser(parser, 'key = :',                           'key', ':', None)
    test_parser(parser, 'key  =  :',                         'key', ':', None)
    test_parser(parser, ' key  =  : ',                       'key', ':', None)
    test_parser(parser, 'key:=',                             'key', '=', None)
    test_parser(parser, 'key :=',                            'key', '=', None)
    test_parser(parser, 'key: =',                            'key', '=', None)
    test_parser(parser, 'key : =',                           'key', '=', None)
    test_parser(parser, 'key  :  =',                         'key', '=', None)
    test_parser(parser, ' key  :  = ',                       'key', '=', None)
    test_parser(parser, 'key==',                             'key', '=', None)
    test_parser(parser, 'key ==',                            'key', '=', None)
    test_parser(parser, 'key= =',                            'key', '=', None)
    test_parser(parser, 'key = =',                           'key', '=', None)
    test_parser(parser, 'key  =  =',                         'key', '=', None)
    test_parser(parser, ' key  =  = ',                       'key', '=', None)
    test_parser(parser, 'key::',                             'key', ':', None)
    test_parser(parser, 'key ::',                            'key', ':', None)
    test_parser(parser, 'key: :',                            'key', ':', None)
    test_parser(parser, 'key : :',                           'key', ':', None)
    test_parser(parser, 'key  :  :',                         'key', ':', None)
    test_parser(parser, ' key  :  : ',                       'key', ':', None)
    test_parser(parser, 'key="value"',                       'key', 'value', None)
    test_parser(parser, 'key  =  "value"',                   'key', 'value', None)
    test_parser(parser, ' key  =  "value" ',                 'key', 'value', None)
    test_parser(parser, 'key=" value "',                     'key', ' value ', None)
    test_parser(parser, 'key  =  " value "',                 'key', ' value ', None)
    test_parser(parser, ' key  =  " value " ',               'key', ' value ', None)
    test_parser(parser, "key='value'",                       'key', 'value', None)
    test_parser(parser, "key  =  'value'",                   'key', 'value', None)
    test_parser(parser, " key  =  'value' ",                 'key', 'value', None)
    test_parser(parser, "key=' value '",                     'key', ' value ', None)
    test_parser(parser, "key  =  ' value '",                 'key', ' value ', None)
    test_parser(parser, " key  =  ' value ' ",               'key', ' value ', None)
    test_parser(parser, 'key="',                             'key', '"', None)
    test_parser(parser, 'key  =  "',                         'key', '"', None)
    test_parser(parser, ' key  =  " ',                       'key', '"', None)
    test_parser(parser, 'key = \'"value"\'',                 'key', '"value"', None)
    test_parser(parser, 'key = "\'value\'"',                 'key', "'value'", None)
    test_parser(parser, 'key = ""value""',                   'key', '"value"', None)
    test_parser(parser, 'key = \'\'value\'\'',               'key', "'value'", None)
    test_parser(parser, 'key="value',                        'key', '"value', None)
    test_parser(parser, 'key  =  "value',                    'key', '"value', None)
    test_parser(parser, ' key  =  "value ',                  'key', '"value', None)
    test_parser(parser, 'key=value"',                        'key', 'value"', None)
    test_parser(parser, 'key  =  value"',                    'key', 'value"', None)
    test_parser(parser, ' key  =  value " ',                 'key', 'value "', None)
    test_parser(parser, "key='value",                        'key', "'value", None)
    test_parser(parser, "key  =  'value",                    'key', "'value", None)
    test_parser(parser, " key  =  'value ",                  'key', "'value", None)
    test_parser(parser, "key=value'",                        'key', "value'", None)
    test_parser(parser, "key  =  value'",                    'key', "value'", None)
    test_parser(parser, " key  =  value ' ",                 'key', "value '", None)
    test_parser(parser, 'key ',                              'key', None, None)
    test_parser(parser, 'key',                               'key', None, None)
    test_parser(parser, 'key  ',                             'key', None, None)
    test_parser(parser, ' key     ',                         'key', None, None)
    test_parser(parser, 'key=value#comment ',                'key', 'value#comment', None)
    test_parser(parser, 'key=value #comment',                'key', 'value', 'comment')
    test_parser(parser, ' key  =  value  #  comment',        'key', 'value', 'comment')
    test_parser(parser, 'key:value#comment',                 'key', 'value#comment', None)
    test_parser(parser, 'key:value #comment',                'key', 'value', 'comment')
    test_parser(parser, ' key  :  value  #  comment',        'key', 'value', 'comment')
    test_parser(parser, 'key=value;comment ',                'key', 'value;comment', None)
    test_parser(parser, 'key=value ;comment',                'key', 'value', 'comment')
    test_parser(parser, ' key  =  value  ;  comment',        'key', 'value', 'comment')
    test_parser(parser, 'key:value;comment',                 'key', 'value;comment', None)
    test_parser(parser, 'key:value ;comment',                'key', 'value', 'comment')
    test_parser(parser, ' key  :  value  ;  comment',        'key', 'value', 'comment')
    test_parser(parser, 'key = value # comment # comment',   'key', 'value', 'comment # comment')
    test_parser(parser, 'key = "value # comment" # comment', 'key', 'value # comment', 'comment')
    test_parser(parser, 'key = "#" ; comment',               'key', '#', 'comment')
    test_parser(parser, 'key = ";" # comment',               'key', ';', 'comment')

**Comment by jolastar** [comment]
I also think it's important to be able to specify an empty string in the config file.

@macfreek's proposal seems exactly right and should be the implemented regex for parsing the config file.

**Comment by macfreek** [comment]
This has been a while.

I'm happy to make a pull request, but have one question.
Looking into the code, one difference is that the improved version is more restrictive in what type of keys are allowed, from currently `[^:=;#\s]+?` (any character except spaces, =, : , ; ,:, #) to `\w+?` (any word-letter). This validates all keys, except perhaps a few.

My question: what characters are allowed in a key? a...z, A...Z, 0...9, _ are a given. But is a hyphen allowed? Thus, is "key-word" also a valid key? I can easily add a hyphen. Are there other valid non-word characters? E.g. "key@word", "key!word", "key^word", key*word", etc.
