### ISSUE TITLE
Allow specifying config file argument without suffix

### ISSUE THREAD

**Issue by danielhers** [bw2/ConfigArgParse#106]
My use case is that I have a `--model` argument to my program, which contains data to be loaded when the program starts and saved when the program ends. I would like to add a config file whose name is just the model filename + a `.yml` suffix, without the user having to specify that explicitly.
This could be accomplished by making the `--model` argument a `is_config_file_arg=True` argument, except that then the model file itself will be treated as the config, where I want the file with the `.yml` suffix to be taken. For that a default suffix to add to `is_config_file_arg=True` arguments would be helpful.

**Comment by bw2** [comment]
This is a pretty niche use-case, so I'd rather not add args to the API unless more people need this.  
You should also be able to get this behavior by subclassing configargparse.ArgumentParser, over-riding `_open_config_files` and modifying the `command_line_args` before passing them to super. _open_config_files(..)
