### ISSUE TITLE
PyPI version is out of date

### ISSUE THREAD

**Issue by iLoveTux** [bw2/ConfigArgParse#112]
To start thank you very much for your work on ConfigArgParse, I just found this package and it has allowed me to simplify a number of my applications.

Currently the release on PyPI is broken in as much as it will not parse lists from an environment variable such as

`C:\> set OPTION=[first,second]`

but if I install latest revision from github like so:

`C:\> pip install git+https://github.com/bw2/ConfigArgParse`

then it works as expected, so I'm assuming that the behavior has been fixed but the version on PyPI is not up to date with github.

This is an issue because I would like to declare ConfigArgParse as a dependency in setup.py, but that will make it install the version in PyPI.

I wish this was something that I could submit a PR for, but I don't think that I can.

**Comment by achimnol** [comment]
I just also noticed that parsing "0" or "1" as boolean flags is already patched in the master version but not on the PyPI version. 😞

**Comment by bw2** [comment]
PyPI version updated to 0.13 (https://pypi.python.org/pypi/ConfigArgParse)
