### ISSUE TITLE
default for default_config_files=[...]

### ISSUE THREAD

**Issue by guettli** [bw2/ConfigArgParse#12]
I look at the README and see this:

p = configargparse.ArgParser(default_config_files=['/etc/settings.ini', '~/.my_settings'])

I think: everybody is going to have a different list here.

But I guess there could be a default which satisfies a lot of people.

My prefered API: just provide a basename.

Then the library checks below os.environ['VIRTUAL_ENV'], os.environ['HOME'], '/etc'.

Of course the new feature should not make old code break.

**Comment by bw2** [comment]
this might be a matter of style, but in this case I err on the side of allowing more control than reducing the size of the list people provide.
