### ISSUE TITLE
missing SUPPRESS

### ISSUE THREAD

**Issue by jsf80238** [bw2/ConfigArgParse#13]
Changed my program as follows:
import configargparse as argparse

And now:

$ tag -h
Traceback (most recent call last):
  File "/home/user/make-deployment-group.py", line 31, in <module>
    parser.add_argument("--user-name", help=argparse.SUPPRESS)
AttributeError: 'module' object has no attribute 'SUPPRESS'

**Comment by bw2** [comment]
somehow forgot to include those.. thanks for reporting this.

**Comment by bw2** [comment]
This has been fixed. 
If no further feedback, this issue will be closed as soon as I push v0.9.4 to PyPI.
