### ISSUE TITLE
Specify --config in default config

### ISSUE THREAD

**Issue by felix1m** [bw2/ConfigArgParse#135]
Is it possible to set the config path in a default file?

E.g.:
    p = configargparse.ArgParser(default_config_files=['~/.my_default_config.conf'])
    p.add('-c', '--config', required=False, is_config_file=True, help='config file path')

with .my_default_config.conf having the line
config=/etc/myapp/config1.conf

At the moment the file /etc/myapp/config1.conf will not be loaded.

Can i first parse the defaults somehow before parsing the rest?

**Comment by ronhanson** [comment]
Hi @felix1m ,
You want to specify a config file path within a config file?
Why don't you just set : 

```
p = configargparse.ArgParser(default_config_files=[' /etc/myapp/config1.conf'])
p.add('-c', '--config', required=False, is_config_file=True, help='config file path')
```

to set ``` /etc/myapp/config1.conf``` as your config file of choice already?
Tell me if I misunderstood something.

**Comment by felix1m** [comment]
Hi, thanks for your quick! 

Yes, thats's what i'm currently doing by moving config files around to /etc/myapp/config.conf.

The reason i'm asking is that i have 5 different files, like: /etc/myapp/config[1-5].conf
so i'd like to switch between them easily

**Comment by ronhanson** [comment]
You can use the command line to override the default config file : 

```> my_program.py -c /etc/myapp/config2.conf ```

This will override the default file setup in ```/etc/myapp/config1.conf```. Would that work for you or do you need another file to edit that would contain the location of your actual config file to use? If so, I would advise you to open a file descriptor pointing to a file where you store the config file location in raw txt. But still that sound weird to me.

**Comment by ronhanson** [comment]
@felix1m Did that help you? Still having issues?

**Comment by felix1m** [comment]
I resolved it by adding a whole directory to the list of default config files.
So now it it is one default file and one dir of optional files.

This is actually very similiar to a lot of linux tools, e.g.:
/etc/default/openvpn.conf
/etc/openvpn/*.conf 

This way i can switch the config files around without loosing their name.

This is an acceptable solution for our case.
Thanks a lot for your support!
