### ISSUE TITLE
DefaultConfigFileParser does not handle empty strings

### ISSUE THREAD

**Issue by ned14** [bw2/ConfigArgParse#136]
If I default an argument to an empty string "", and write the config file, items appear as

```
argname =
```

... which is fine. If I run the program, loading the config file and writing it back out again, I now get

```
argname = =
```

The YAMLConfigFileParser does not suffer from this problem. It outputs '' for empty strings.

**Comment by jolastar** [comment]
The cause is that `argname =` is interpreted as setting `argname` to `=` (and `argname=` is invalid).

See #103 which points out the issue and provides a code snippet as a workaround.
