### ISSUE TITLE
Dash not supported as first character of argument string when using --arg=value

### ISSUE THREAD

**Issue by lohedges** [bw2/ConfigArgParse#137]
Thanks for the fantastic package, it has been of great help to my project.

One wrinkle that I've come across is that, unlike `argparse`, `configargparse` doesn't seem to support a dash as the first character of an argument when using `--arg=value` syntax. As a minimal example, consider the following script:

```python
# test.py
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--temperature", required=True)
args = parser.parse_args()
print(args)
```

With `argparse`, as long as we use `--arg=value`, all of the following work:

```bash
python test.py --temperature=-10C
python test.py --temperature="-10C"
```

(In my code the parser is extremely flexible with the syntax that it allows for inputs and can convert from strings to any internal type, e.g. the user can write the temperature however they like, and in whatever unit.)

However, this doesn't work with `configargparse`:

```python
# test.py
import configargparse as argparse

parser = argparse.ArgumentParser()
parser.add_argument("--temperature", required=True)
args = parser.parse_args()
print(args)
```

```bash
python test.py --temperature=-10C
python test.py --temperature="-10C"
```

Gives:

```bash
usage: test.py [-h] --temperature STRING
test.py: error: argument --temperature: expected one argument
```

i.e. the dash is being interpreted as another short-form argument.

As a workaround I'm currently just asking users to escape the dash, or to put a space before, e.g.:

```bash
python test.py --temperature="\-10C"
python test.py --temperature=" -10C"
```

Is there any reason why the behaviour differs between the two packages?

Cheers.

**Comment by ronhanson** [comment]
Thanks for reporting.
I'll take a look at this.
PR welcome if by any chance you know where to find the issue.

**Comment by Savlik** [comment]
This is caused by normalizing arguments (https://github.com/bw2/ConfigArgParse/blob/master/configargparse.py#L400), which loses some information. In argparse `--foo=-bar` works, but `--foo -bar` does not. This is because argparse thinks, that `-bar` is separate argument. 
I am not sure if I understand the code enough to fix this and create PR, but I can try.
