### ISSUE TITLE
Exception with action=count if count is above 1

### ISSUE THREAD

**Issue by Wyrmwood** [bw2/ConfigArgParse#138]
Normally used for verbosity, arguments like
-vv 
where the action=count will throw an exception because it falls under ACTION_TYPES_THAT_DONT_NEED_A_VALUE, but the handler for that assumes 
Expecting 'true', "
                           "'false', 'yes', 'no', '1' or '0'"
which won't handle anything above -v

**Comment by ronhanson** [comment]
Thanks for reporting the bug.
I'll try to take a look at this. Ping me if no news in a while.
Otherwise, PR accepted.

**Comment by Wyrmwood** [comment]
I will probably end up using something homebrew. While I like this project and concept, in my case, I need to handle arguments where the mapping doesn't directly go to the same destination name, so I'm ending up with a config that won't parse all the arguments properly as input to the parser.

**Comment by MarcelWaldvogel** [comment]
I have a debug option with similar behavior and was trying to set `debug=2` in the config file, running into the same problem.

So it would be handy if `action='count'` would not need to repeat the entries in the config file but could assign directly as well.

**Comment by christensonb** [comment]
I solved this problem with something like this
```
            elif isinstance(action, _CountAction):
                for arg in args:
                    if any([arg.startswith(s) for s in action.option_strings]):
                        value = 0
                args += [action.option_strings[0]] * int(value)
```
