### ISSUE TITLE
feature - automatic env variables

### ISSUE THREAD

**Issue by wwalker** [bw2/ConfigArgParse#15]
I'd like to have an app where command line arguments, config file keys, and env vars are all "the same"

Given an app named "foo_bar", and command line options --single --multiple-word, without passing env_var, these config file keys would work (current behavior):

single = lonely
multiple-word = logorrhea

and these env vars would be automatic:

FOO_BAR__SINGLE=finally
FOO_BAR__MULTIPLE_WORD=unending

I used two underscores to separate the uniqueness prefix (FOO_BAR (defaulting to the uppercase app name)) but it could be one.

p = configargparse.ArgParser(automatic_env_vars=true)

p = configargparse.ArgParser(automatic_env_vars=true, env_var_prefix='FOO_BAR')

**Comment by bw2** [comment]
This has been implemented. 
If no further feedback, this issue will be closed as soon as I push v0.9.4 to PyPI.
