### ISSUE TITLE
Regular expression strings should be raw strings

### ISSUE THREAD

**Issue by johann-petrak** [bw2/ConfigArgParse#153]
E.g. the expression 
`key = "(?P<key>[^:=;#\s]+?)"`
 in the parse() method around line 160 should really be 
`key = r'(?P<key>[^:=;#\s]+?)'`

**Comment by macfreek** [comment]
I think this was fixed in commit 6267759 (which was actually dated from 13 Feb 2019, before this issue).

My suggestion would be to close this issue, with the suggestion to reopen if there still is a problem.
