### ISSUE TITLE
Combination of nargs='+' and type=float fails when reading from config file

### ISSUE THREAD

**Issue by jolehton** [bw2/ConfigArgParse#16]
I love the work you've done with this package, it has spared me from so many parsing-induced headaches.

I did, however, run into a slight problem with the nargs-option (using ConfigArgParse 0.9.3). If I have a file foo.py and I add an argument with `parser.add('--bar', type=float, nargs='+')`, then the following works as expected:

```shell
./foo.py --bar 1.0 2.0 3.0
```

However, having `bar = 1.0 2.0 3.0` in the config file conf.ini does not work:

```shell
./foo.py --conf conf.ini
foo.py: error: argument --bar: invalid float value: '1.0 2.0 3.0'
```

As far as I understand it from reading the source code, the problem arises because config file values are passed to argparse as a single string, so the config file setting above would actually be equivalent to

```shell
./foo.py --bar "1.0 2.0 3.0"
foo.py: error: argument --bar: invalid float value: '1.0 2.0 3.0'
```

This of course fails since that string is not a valid float.

**Comment by gabyx** [comment]
I expecting the same issue,
would be nice to specify
```
bar =[ 1.0,2.0, 3.0]
```
and allow  ``nargs="+"`` or ``nargs=3`` and an error would generated if the list is longer

**Comment by bw2** [comment]
coalesced into #30
