### ISSUE TITLE
configparser based ConfigFileParser

### ISSUE THREAD

**Issue by josephcarmack** [bw2/ConfigArgParse#172]
Currently the only ConfigFileParsers available are DefaualtConfigFileParser and YAMLConfigFileParser. These are nice but neither supports multi-line values. This is really needed if you are going to have lists and dictionaries as values because formatting them in a single line quickly becomes unreadable with anything but the smallest of lists/dicts.

This could easily be addressed if a ConfigFileParser was contributed that parsed files with python's native configparser module which comes as part of the python stdlib. I think adding such a ConfigFileParser subclass with this support would greatly expand the cabilities and features of this package.

**Comment by josephcarmack** [comment]
I was incorrect in my statement that the YAMLConfigParser does not support multi-line values. It in fact does. Regardless, I still think having a ConfigFileParser that uses python's native configparser package for parsing is a useful extension as it allows use of a broader set of config file syntax users may want with respect to INI style formatting.

**Comment by bw2** [comment]
Thanks. Merged.

**Comment by bw2** [comment]
If you have a chance to add docs to this section
https://github.com/bw2/ConfigArgParse#config-file-syntax
that would be appreciated.
