### ISSUE TITLE
action='count' doesn't work with config

### ISSUE THREAD

**Issue by dmartin-isp** [bw2/ConfigArgParse#175]
p.add('--verbose', '-v', action='count', default=0 )

set verbose to 4 in the config file and you get:

error: Unexpected value for verbose: '4'. Expecting 'true', 'false', 'yes', 'no', '1' or '0'

https://github.com/bw2/ConfigArgParse/blob/master/configargparse.py#L739

**Comment by bw2** [comment]
If you want to add better handing for argparse._CountAction, a PR would be appreciated.

**Comment by macfreek** [comment]
I think this is a duplicate of #138
