### ISSUE TITLE
Cannot use nargs with action=append

### ISSUE THREAD

**Issue by davistardif** [bw2/ConfigArgParse#177]
Argparse allows me to create an argument like so:
```
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--foo', nargs=2, action='append') 
_AppendAction(option_strings=['--foo'], dest='foo', nargs=2, const=None, default=None, type=None, choices=None, help=None, metavar=None)
>>> parser.parse_args('--foo 1 2 --foo 3 4'.split())
Namespace(foo=[['1', '2'], ['3', '4']])
>>> 
```

But using an argument like this doesn't seem to work with configargparse:
```
>>> import configargparse
>>> import yaml
>>> parser = configargparse.ArgumentParser(
...     config_file_parser_class=configargparse.YAMLConfigFileParser)
>>> parser.add_argument('--foo', nargs=2, action='append')
_AppendAction(option_strings=['--foo'], dest='foo', nargs=2, const=None, default=None, type=None, choices=None, help=None, metavar=None)
>>> with open('temp.yaml', 'w') as f:
...     yaml.safe_dump({'foo': [1, 2]}, f)
... 
>>> parser.add_argument('--config', is_config_file=True)
_StoreAction(option_strings=['--config'], dest='config', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
>>> parser.parse_args(['--config', 'temp.yaml'])
usage: [-h] [--foo FOO FOO] [--config CONFIG]
: error: argument --foo: expected 2 arguments
```

It doesn't seem unreasonable to have `nargs` and `action='append'` used together. The config file could represent this with a nested list.

**Comment by bw2** [comment]
Putting aside the fact that argparse allows it, why would you want to do this?

**Comment by davistardif** [comment]
Suppose you wanted to be able to parse something like 
`command --person john smith --person jane doe`
Having `nargs=2` ensures that there is a first name and last name supplied and argparse will split them for you and having `action=append` lets you supply more than one value for the argument.

I'm currently working on a project where I need to use this kind of setup. The user supplies one or more pairs of the name of a docker image and npm package

**Comment by bw2** [comment]
Hmm.. I would personally prefer --person "john smith" --person "jane doe" in that situation, and split them myself, but if it doesn't add much complexity to fix this, a PR would be appreciated.

**Comment by davistardif** [comment]
Bump

I added a PR, it's a pretty simple fix.

**Comment by bw2** [comment]
Sorry for the delay. Just merged.
