### ISSUE TITLE
Bug of 1.2: AttributeError: 'NoneType' object has no attribute 'nargs'

### ISSUE THREAD

**Issue by kamo-naoyuki** [bw2/ConfigArgParse#179]
https://github.com/bw2/ConfigArgParse/blob/21f689b1dbd522bfd59fbdbfdcea2fe5629153e7/configargparse.py#L744-L746

Suggestion:

```python
 accepts_list = (isinstance(action, argparse._StoreAction) and 
                 action.nargs in ('+', '*')) or (
                 isinstance(action, argparse._StoreAction) and
                     isinstance(action.nargs, int) and action.nargs > 1)
```

**Comment by kamo-naoyuki** [comment]
Why did you close? This bug is not fixed.

**Comment by bw2** [comment]
I thought #1764 fixed this?

**Comment by kamo-naoyuki** [comment]
???
#1764 is not related to configargparse.

**Comment by kamo-naoyuki** [comment]
This is a simple bug as I wrote. Please fix quickly. Affecting many people.

**Comment by bw2** [comment]
Thank you for the suggested fix. In the future, please submit a PR instead.

**Comment by kamo-naoyuki** [comment]
Thank you!
