### ISSUE TITLE
Config file support for arguments with no long version (e.g. subparsers)

### ISSUE THREAD

**Issue by netw0rkf10w** [bw2/ConfigArgParse#183]
Hello,

Thanks for making this tool freely available!

In the current version, it is really a pity that one cannot use arguments that do not have a long version (i.e. start with `--`). This completely rules out the use of subparsers.

Consider the following script for example:

```python
import configargparse as argparse

def main():
    parser = argparse.ArgumentParser(description='Test')
    parser.add('--cfg', default=None, is_config_file=True, help='training configuration file')

    subparsers = parser.add_subparsers(help='Argument for dataset', dest='dataset', required=True)
    toto_parser = subparsers.add_parser('toto')
    toto_parser.add_argument('toto_path', help='Path to dataset.')
    tata_parser = subparsers.add_parser('tata')
    tata_parser.add_argument('tata_path', help='Path to dataset.')

    parser.add_argument('--some-arg', type=int, default=-1, help='some other argument')

    args = parser.parse_args()
    print(parser.format_values())
if __name__ == "__main__":
    main()
```

It is not possible to define the arguments `toto` or `tata` in a config file. 

Could you please add this feature? Thank you very much in advance!

**Comment by bw2** [comment]
Sorry, this seems like a rare use case that would be complicated to support.

**Comment by netw0rkf10w** [comment]
@bw2 Thanks for the reply. I thought it was simple, but if it's too complicated then never mind. Let me close the issue.
