### ISSUE TITLE
arguments with config file string True get automatically converted to bool

### ISSUE THREAD

**Issue by gabyx** [bw2/ConfigArgParse#19]
Supposed we have the following in the INI files:
```
value = True
```
and the add command

```
p.add( "-v","--value", type=str, default="False" ) 
```
This results in an error  ``value set to 'True' rather than a value
``(see below line 322)
But the user said it wants to have a type ``str``. So it should be parsed as a string in any case and not transformed into bool automatically, this should only happen if the user did not specify a type , or really requested a type bool. (suggestion)
(I need this to happens since I reuse the parsed stuff to interpolate  with other parsed ini files somewhere else in the code, and to make that happen everything needs to be strings )

I would use the following safe bool conversion:

```
def toBool(self,s, optionHint=None):
        """Safe converting to a boolean value, raises exception if s has wrong type or does not have the appropriate value"""
        if type(s) == str:
            try:
                if ['true','yes','on','false','no','off'].index(s.lower()) <= 2:
                    return True
                else:
                    return False
            except:
                raise ValueError("Value: %s %s !" % (s, "at option: %s" % optionsHint if optionHint else ""))
        else:
            raise ValueError("Converting type: %s with value: %s to bool is deliberately not supported!" % (type(s),s))
```

It would be good to be able to not automatically convert  to bool here (line 322):
in ``convert_setting_to_command_line_arg``
```
if value.lower() == "true":
            if type(action) not in ACTION_TYPES_THAT_DONT_NEED_A_VALUE:
                self.error("%s set to 'True' rather than a value" % key)
            args.append( action.option_strings[-1] )
``

**Comment by bw2** [comment]
Thanks gabyx. This a great point.

**Comment by gabyx** [comment]
Thanks a lot, lookin forward to the improvements :-)
:+1:
