### ISSUE TITLE
Behavior of parse_args() with existing namespace object

### ISSUE THREAD

**Issue by dbachran** [bw2/ConfigArgParse#191]
Disclaimer: I'm somewhat new to Python. ;-)

I wanted to add some additional command line arguments to an existing namespace object. The underlying end goal was to query to the user interactively for any arguments, which are not specified in a config file, env var, or on command line. But, those arguments are to be considered "mandatory" by our script and are thus queried interactively.

The method `parse_args()` supports to specify both `args` and `namespace`. My assumption was the following:
- The first time I am running `cfg.parse_args()` I get a namespace object `args`
- I want to add two additional arguments to `args`
- I build a custom `command_line` (like `--missing-argument-one --missing-argument-two=addme`
- I run `args = cfg.parse_args(command_line, args)`

Expected results:
- My namespace object `args` does contain all arguments from the first, intial `cfg.parse_args()` call **and** all arguments from the second call (where I specified additional command line arguments)
- Further operations on `cfg` do honor all combined arguments within `args`, e.g. when calling `cfg.write_config_file(args, ...)`

Actual results:
- My namespace object `args` does indeed contan all combined arguments (i.e. first call + second call to `cfg.parse_args()`)
- But, further operations on `cfg` do only know about the arguments from the second call to `cfg.parse_args()`, all arguments from the first call seem to have been forgotten

Full example code snippet:
```python
args = cfg.parse_args()
missing_argument = getpass.getpass("Please enter MISSING-ARGUMENT ").strip()
interactive_arguments += ' --missing-argument=' + missing_argument
args = cfg.parse_args(interactive_arguments, args)
cfg.print_values()
cfg.write_config_file(args, [config_file])
```

In the example above, `args` does indeed contain all combined arguments. But, wen running `cfg.print_values()` and `cfg.write_config_file()` only the new arguments within `interactive_arguments` are honored.

**Comment by dbachran** [comment]
I created a quick pull request to show the desired changes, from my point of view at least... ;-)

**Comment by bw2** [comment]
@dbachran This sounds like a very niche use-case, and I don't think it should go within configargparse. You might try subclassing the ArgumentParser class in your own code and overriding the `parse_known_args` method.

**Comment by dbachran** [comment]
Hm... If you think this is a nice use-case, I would at least suggest to update the documentation on the expected behaviour of `cfg.parse_args()`. To me the actual behaviour sounds like a bug. But perhaps that is just me...?

Best regards,
Daniel :-)
