### ISSUE TITLE
Option to prioritize config file over args 🧐

### ISSUE THREAD

**Issue by TGotwig** [bw2/ConfigArgParse#194]
Currently, if the same key thorugh a config file and thorugh the args was passed,
the value from the args has priority,
an option would be nice to give the key/value inside the config file the priority.

For instance this would be good for a Makefile inside a Version Control System, where you have lots of default arguments to run a python script with, but you want to overwrite some key/values by a config file 🙂

**Comment by bw2** [comment]
This goes against convention and think it's too niche of a use-case to add to configargparse. If you need this behavior, I would recommend extending/subclassing the library to add it.
