### ISSUE TITLE
How to disable environment variable reading?

### ISSUE THREAD

**Issue by ajupazhamayil** [bw2/ConfigArgParse#195]
I would like to disable environment variable reading. Is it possible to do so? If yes how?

**Comment by bw2** [comment]
I'm not sure I understand the question. Environment variables are only read when explicitly specified for particular args. See the README example - particularly this line:

```
p.add('-d', '--dbsnp', help='known variants .vcf', env_var='DBSNP_PATH') 
```
It's the only one that defines an env. var.
