### ISSUE TITLE
List type parameters should be appended to by command line argument, not replaced

### ISSUE THREAD

**Issue by AMNeumann** [bw2/ConfigArgParse#196]
Consider the following script:
```python
import configargparse

parser = configargparse.ArgParser(config_file_parser_class=configargparse.YAMLConfigFileParser)
parser.add('-a', '--arg', action='append')
parser.add('-c', '--config', is_config_file=True)
args = parser.parse_args()

print(args)
```

Add a config file to the mix:
```yaml
arg: [foo, bar]
```

And call like this:
```python test.py -c test.yaml -a baz```

I'm getting
```Namespace(arg=['baz'], config='test.yaml')```

But I would like this:
```Namespace(arg=['foo', 'bar', 'baz'], config='test.yaml')```

I know this goes against the principles of configargparse for all other kinds of options, but still, it seems reasonable to me for append options.

**Comment by bw2** [comment]
Unless more people want this, I would recommend extending/subclassing configargparse to add it as a feature for your project. Although what you're proposing is reasonable, without interest from more users, it's like adding too many knives to the swiss-army knife.
