### ISSUE TITLE
Allow getting values from a specific section of config file

### ISSUE THREAD

**Issue by ethanmcc** [bw2/ConfigArgParse#20]
I have a use case where my config file has a DEFAULT section, then a section for each code environment (test, dev, qa, etc.). I see in the documentation that you recommend not forcing users to put settings in specific sections, but in this case am I defining the same variables in each section. Is there a way to have my values merge only with one section? For example, I might have:

    [DEFAULT]
    color = blue

    [dev]
    name = Simon

    [qa]
    color = red
    name = Bill

When my environment is dev, I'm going to want color: blue, name: Simon, with the possibility of overriding either from the CLI. Am I missing this functionality, or is it something you might accept a pull request for?

**Comment by bw2** [comment]
I don't see a straight-forward way to support this use case directly. If I understand it correctly, there would need to be new methods or args added to the API for specifying which section to get values from as well as a bunch of implementation code specific to this feature. 

Instead, could you just have separate files: default.conf, dev.conf, qa.conf, etc and just select the right one to pass in on the command line?

**Comment by ethanmcc** [comment]
Thanks for the response. I ended up implementing this using a combo of ConfigParser and argparse. There was enough custom logic there that it seems difficult to write a general case. Separate files is probably the way to go.

**Comment by tristanlatr** [comment]
This is a duplicate of https://github.com/bw2/ConfigArgParse/issues/250, in which I proposed a simple and maintainable solution to support configuration sections.
