### ISSUE TITLE
ModuleNotFoundError: No module named 'ConfigArgparse' on MacOS Big Sur

### ISSUE THREAD

**Issue by nospam2k** [bw2/ConfigArgParse#204]
See next entry

**Comment by nospam2k** [comment]
Sorry, my mistake. I didn't see the configargparse.py file. I'm assuming that is correct. So the actual problem is this.

python3 -c "import ConfigArgparse"   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ConfigArgparse'

Yet pip3 list shows:
Package        Version
-------------- ---------
certifi        2020.12.5
chardet        4.0.0
ConfigArgParse 1.2.3
idna           2.10
pip            20.3.3
requests       2.25.1
setuptools     41.2.0
six            1.15.0
urllib3        1.26.2
wheel          0.33.1

**Comment by nospam2k** [comment]
Ok, if I just put configargparse.py in the same dir as I run the command it works and if I go into /Users/david/Library/Python/3.8/lib/python/site-packages and run the command there, it also works.

**Comment by bw2** [comment]
This seems to me like a problem of more than one python version installed, or PYTHONPATH set incorrectly.
