### ISSUE TITLE
Add multiline YAML (and/or INI).

### ISSUE THREAD

**Issue by bartekbrak** [bw2/ConfigArgParse#23]
YAML supports multiline input (https://gist.github.com/rjattrill/7523554) and lists (http://docs.ansible.com/YAMLSyntax.html#yaml-basics) but neither of those can be used in the ini file:

    listoffruits:
        - Apple
        - Orange
    theelements: >
        [my_extraorbitantly_long_element_address1,
        my_extraorbitantly_long_element_address2,
        my_extraorbitantly_long_element_address3]

these produce errors. I mainly wanted to use your library because I expect user to provide tens of long strings as configuration. Putting them in one-line would clutter the INI file. 

Do you consider such feature useful and would like to implement it?

 I also didn't find a way to provide an INI style multiline content but this is not officially supported (INI is not even a well defined standard and the most formal definitions I saw didn't mention multiline though some libs allow that with indentation).

**Comment by bw2** [comment]
coalesced into #30
