### ISSUE TITLE
singleton -h and --help only show the first group of options to be parsed

### ISSUE THREAD

**Issue by grimmy** [bw2/ConfigArgParse#24]
Using the singleton option from the readme results in the following

    $ python main.py --help
    usage: main.py [-h] [--utils-setting UTILS_SETTING]

    optional arguments:
      -h, --help            show this help message and exit
      --utils-setting UTILS_SETTING
                            Config-file-settable option for utils (default: None)

As you can see the main options aren't added because the -h is being processed by the first p.parse_known_args.  Basically this make this great feature useless.

I've tried using a named parser too and got the same result.

I think a decent fix would be to not process -h until you hit a parse_args and completely ignore it in parse_known_args, but I haven't looked at the code at all to see how feasible that is.

**Comment by lahwaacz** [comment]
Actually the example is wrong here. Parsing the arguments in the utils.py module's global scope is the problem which causes this behaviour. To improve the example, just move the parsing to local scope, e.g. a function:

main.py
``` python
import configargparse
import utils

p = configargparse.getArgumentParser()
p.add_argument("-x", help="Main module setting")
p.add_argument("--m-setting", help="Main module setting")
options = p.parse_known_args()   # using p.parse_args() here may raise errors.

print("from main.py:", options)
utils.main()
```

utils.py
``` python
import configargparse
p = configargparse.getArgumentParser()
p.add_argument("--utils-setting", help="Config-file-settable option for utils")

def main():
    options = p.parse_known_args()
    # do something with the options
    print("from utils.py:", options)
```
Then `python main.py --help` produces the output you expected and `python main.py -x anything` produces
```
$ python main.py -x anything
from main.py: (Namespace(m_setting=None, utils_setting=None, x='anything'), [])
from utils.py: (Namespace(m_setting=None, utils_setting=None, x='anything'), [])
```

**Comment by bw2** [comment]
For cases where you need to get command line arg values to initialize a module at load time, perhaps there should be a new `parse_help_args=True` keyword arg added to `parse_known_args()`? That way, in these cases, it could be set =False (except in the main script).

**Comment by lahwaacz** [comment]
Why would someone want to initialize a module based on command-line arguments? This would have already been implemented in argparse if it were considered a good practice...

**Comment by bw2** [comment]
I agree that would be rare. I'll close this for now unless this request gets more interest.
