### ISSUE TITLE
Is it possible to show default values of parameter like argparse does?

### ISSUE THREAD

**Issue by stastnypremysl** [bw2/ConfigArgParse#244]
Hello.

Is it possible to automatically print default values of optional parameters to help please?

Thanks.
Přemysl

**Comment by bw2** [comment]
Have you tried setting formatter_class=argparse.ArgumentDefaultsHelpFormatter ?
eg. `configargparse.ArgumentParser(formatter_class=configargparse.ArgumentDefaultsHelpFormatter)`
