### ISSUE TITLE
Feature: Parse additional config file information to be merged into existing config object

### ISSUE THREAD

**Issue by kesmit13** [bw2/ConfigArgParse#25]
Maybe this is possible already, but it isn't obvious.  I'd like to parse arguments and config files at startup, but then add an additional config (either file or string contents of file) at a later time.  The existing config would be updated with the settings from the new information.

**Comment by bw2** [comment]
This is a hack, but should work:
```
parser = configargparse.Parser(..)
initial_args = parser.parse_args()

parser._default_config_files.append("config_file2.ini")
updated_args = parser.parse_args()
```
If this is useful (especially to more than one person) I could add a method like `add_config_file(..)` to the api.
