### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by darkdragon-001** [bw2/ConfigArgParse#278]
There hasn't been any commits in the past year and there are many open unmerged pull requests. Is this project still maintained?

**Comment by DrackThor** [comment]
Wondering the same - is there any official statement from the main contributors?

**Comment by IvanMalison** [comment]
Seems like @bw2 is no longer around. Perhaps a fork should be considered so that work on the project can continue. Seems that there are many willing contributors.

**Comment by bw2** [comment]
I very rarely have time to revisit this repo, but have been updating it every 1 or 2 years. If people are willing to help with more frequent maintenance, please post here. 
I'm looking for someone with a minimalist approach -  primarily interested in fixing critical issues, implementing relatively simple but widely-useful feature requests, and updating the library to work with the latest version of python. 
I would like to keep the core functionality in good shape, while avoiding new excessively complicated features that are only useful for a very small number of users.

**Comment by IvanMalison** [comment]
@bw2 I'm happy to help out.

**Comment by bw2** [comment]
Thanks @IvanMalison !  Can you say more about your interest in this project?
Do you see any specific tasks worth addressing now, or is this an offer for future help?
