### ISSUE TITLE
Create a more robust config file format implemented as a subclass of ConfigFileParser 

### ISSUE THREAD

**Issue by bw2** [bw2/ConfigArgParse#30]
Write a new implementation of ConfigFileParser to provide a more robust alternative to the current config file format which:
- ideally doesn't introduce dependencies on any 3rd party libraries
- allows multiline values (#10, #23 )
- has better support for lists  ( #16 )

This issue combines and closes #10, #16, #23

**Comment by lahwaacz** [comment]
Most importantly this is a direct followup of #21.

**Comment by lahwaacz** [comment]
Is the goal implementing yet another brand new config file format or abstracting the functionality needed for easy development of/interfacing with custom parsers (as mentioned in [this post](https://github.com/bw2/ConfigArgParse/issues/21#issuecomment-128113407))?

**Comment by bw2** [comment]
@lahwaacz - the goal is both. The above pull request would close this issue.
