### ISSUE TITLE
Error with # in setting file values.

### ISSUE THREAD

**Issue by aldarund** [bw2/ConfigArgParse#37]
For example i have
SECRET_KEY=s#
Will produce error
configargparse.ConfigFileParserException: Unexpected line 0 in 123.env:

**Comment by bw2** [comment]
This looks like a bug.
I just merged in a new `configargparse.YAMLConfigFileParser` class which can be passed to the constructor to replace the default `config_file_parser_class=DefaultConfigFileParser`.
It uses `yaml.load(stream)` to parse the config file, which might handle this case better.

**Comment by jayvdb** [comment]
The same is true for `;` .

The regex's are looking for whitespace before the comment start characters `#` and `;`.  If there is no whitespace before it, it fails to parse the comment.  Fixing that is easy...

However, it then means that there is no way to use `#` or `;` in a values.

One backwards compatible way of handling this is to support a stream reader parameter `comment_characters = '#;'`, so clients can choose which comment characters they prefer to have active, and possible also a config variable `comment_characters = #;` which the stream reader will detect and then use until it appears again in the config file.

**Comment by bw2** [comment]
A pull request to support something like `comment_characters = '#;'`
would be appreciated.

**Comment by bw2** [comment]
Please reopen if the fix for #67 doesn't resolve this.
