### ISSUE TITLE
Config file output can generate illigitimate values for keys when using custom Actions

### ISSUE THREAD

**Issue by patternspandemic** [bw2/ConfigArgParse#43]
Cause: [`ArgumentParser.get_items_for_config_file_output`](https://github.com/bw2/ConfigArgParse/blob/master/configargparse.py#L620) makes the incorrect assumption that an argument's config file value can always be found in the parsed namespace's attribute named after `action.dest`. With custom Actions this value can be arbitrary.

Effect: Using the action's computed value rather than the command-line's string value results in a config key-value pair that does not reproduce the original specified options.

```python
class CustomAction(configargparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        setattr(namespace, self.dest, 'arbitrary')

p = configargparse.ArgumentParser(args_for_setting_config_path=['-c'],
                                  args_for_writing_out_config_file=['-w'])
p.add_argument('--number', type=int, dest='result', action=CustomAction)
p.parse_args('--number 2' -w bad.conf)
```

The resulting namespace:
```python
Namespace(result='arbitrary')  # Great, CustomAction did its job
```

But the resulting bad.conf
```ini
number = arbitrary  # This is not going to reproduce
```

Now consider when bad.conf is specified to -c
```
error: argument --number: invalid int value: 'arbitrary'
```
We only recognize the issue due to the type constraint on --number. If there were none, it might be more confusing as to why our option's arg is ignored or worse depending on our action's `__call__` behavior.

The main problem here is the generated config does not reproduce the behavior of the original passed in arguments when passed back in as a config file.

Solution?: Basically we need to store the value passed on the command line to obtain reproducible behavior in situations like this, but it's not clear to me how best to do so. This information is available to the action's `__call__` as arguments, and so could be stored on the parser for later reference in `ArgumentParser.get_items_for_config_file_output`.

Do you think this is a bug?

Thank you,
Brad

**Comment by bw2** [comment]
I'm not sure.. this seems like a rare use case to me, so I'll leave the issue open until a solution is proposed and/or others vote for improving the handling of this.

**Comment by patternspandemic** [comment]
Admittedly, it may add more complexity to the code than it's worth, being the edge case that it is. There likely are other ways to structure argument input in these cases as well, never mind the easy solution of a _human_ edited config file.

I simply wanted to point out the possibility of generating non-reproducible configs with `-w` when using custom Actions. Perhaps a mention in the docs would suffice.

Thanks for taking a look.
Brad

**Comment by bw2** [comment]
Ok, it's great that there are work-arounds. 
I'm not sure how to document this so that it doesn't confuse all the people that aren't using custom Actions - so will just leave it.
