### ISSUE TITLE
Comparison with other packages is out of date

### ISSUE THREAD

**Issue by jayvdb** [bw2/ConfigArgParse#44]
https://pypi.python.org/pypi/ConfArgParse is now 1.1.20 vs 1.0.15

https://pypi.python.org/pypi/appsettings is now 0.7 vs 0.5

https://pypi.python.org/pypi/yconf is now 0.3.3 vs 0.3.2

**Comment by bw2** [comment]
Fixed

**Comment by jayvdb** [comment]
The links have changed but the comparison is still out of date, and refers to the old versions.

**Comment by bw2** [comment]
That section is meant to describe the comparison I did when deciding to implement configargparse as a new project.

**Comment by bw2** [comment]
If you want to do an up-to-date comparison somewhere, I can link to it from the readme.
