### ISSUE TITLE
Optionally allow to address positional arguments

### ISSUE THREAD

**Issue by qua-bla** [bw2/ConfigArgParse#48]
This function should be disabled per default since it might produce problems for some software. I would suggest that the metavar is used as the config parameter.

Probably it is hard to figure out if a config value is a positional argument (and in principle there could be some ambiguity). Maybe 'uppercase' is a good convention to label positional arguments?

**Comment by qua-bla** [comment]
I think this might be a cleaner solution:

- Add support for `env_var` in `add_argument()` for positional arguments.
- Add something like `config_name` in `add_argument()` (maybe only for positional arguments?)

Potential optimizations could be

- Allow `[1,2]` list syntax for nargs>1 not only for action type 'append'
- Also allow a list of names as value for `env_var`

**Comment by bw2** [comment]
sorry, why not just convert your positional arguments to regular key-value arguments?

**Comment by qua-bla** [comment]
Well, the existing borgbackup command line interface (see referenced issue) will probably stay like this for a long time.

After understanding how ConfigArgParse is working, I totally get that it would have to object your design choices. I started an attempt to add the required parts for an overall cleaner implementation to argparse <https://bugs.python.org/issue26394>. This also applies for #49.

Proposing "won't fix" until a partial rewrite of configargparse based on yet to come argparse features has happened.
