### ISSUE TITLE
Positional argument seperator '--' strips config/env values

### ISSUE THREAD

**Issue by qua-bla** [bw2/ConfigArgParse#49]
### `example.py`

```python
import configargparse

p = configargparse.ArgParser()
p.add('--required', required=True, env_var='TEST_REQUIRED')

print(p.parse_args())
```

### Results

```bash
export TEST_REQUIRED=value;

python3 example.py
# Namespace(required='value')

python3 example.py --
# usage: example.py [-h] --required REQUIRED
# example.py: error: the following arguments are required: --required
```

**Comment by bw2** [comment]
My parsing logic clearly has holes, and I haven't thought through how to fix this. Are you pointing this out as a practical issue or as a hypothetical example of how to break the existing code?
If it's a practical issue in your project and you know of a straight forward fix, a pull request would be much appreciated.

**Comment by qua-bla** [comment]
Maybe add this as "known bug" to readme?

**Comment by bw2** [comment]
I can just keep the Issue open. I think people are more likely to look here.

**Comment by dwfreed** [comment]
I can't reproduce this with current Git.  If there are no positional arguments defined, -- is considered an unrecognized argument.  If there is at least one positional argument defined, then -- works normally, regardless of any arguments defined by environment variables.  Could you test with current Git and see if you still have this issue?

**Comment by bw2** [comment]
Thanks @dwfreed for testing this. I also can't reproduce this now.

**Comment by bw2** [comment]
(please reopen if this continues to be an issue)
