### ISSUE TITLE
Change API To conform to PEP 8 names

### ISSUE THREAD

**Issue by bignose-debian** [bw2/ConfigArgParse#51]
There doesn't seem to be a good reason for violating PEP 8 for some of the API.

For example, `configargparse.getArgumentParser` should better be named `configargparse.get_argument_parser` or similar.

**Comment by bw2** [comment]
You're right. Good point.
A pull request would be appreciated (leaving the existing names as aliases for the PEP-8 compliant names, and marked as deprecated).  Or I'll get to this when time allows.

**Comment by bignose-debian** [comment]
My suggested implementation for this is at the branch https://notabug.org/bignose/ConfigArgParse/src/issue/51-api-names (repository at https://notabug.org/bignose/ConfigArgParse/).

I haven't touched the test suite; I wasn't able to get a clean test run even before my changes.
