### ISSUE TITLE
adding certain types of config directives to config files breaks argcomplete tab-completion

### ISSUE THREAD

**Issue by ryran** [bw2/ConfigArgParse#54]
I would love to get some help with this from someone awesome.

https://github.com/kislyuk/argcomplete/issues/123

**Comment by bw2** [comment]
https://github.com/kislyuk/argcomplete is pretty awesome. 
From testing your examples just now, it appears recent configargparse or argcomplete commits have fixed this issue. Are you still it with the latest configargparse?

**Comment by evanunderscore** [comment]
@bw2 The linked examples still fail for me on master and are fixed by #78.
