### ISSUE TITLE
Cannot escape comment characters within value in configuration file

### ISSUE THREAD

**Issue by mindthump** [bw2/ConfigArgParse#60]
For a configuration file ConfigfileParser.parse(), using a semicolon embedded in the value string (my case being SQL connection strings) cause the parser to fail. There should be a way to 1.) turn off comment parsing (the whole line becomes the value) or 2.) escape individual semicolon and hash characters or 3.) quote the value to separate it from comments. (Using 0.10.0 from PyPI)

**Comment by wcastello** [comment]
Is there any side effect to using

`value = white_space+"[:=\s]"+white_space+"(?P<value>.+?)"`

to include ; and # in the values that I didn't notice?

**Comment by bw2** [comment]
This seems fine to me. Thanks for the work-around + example cases.

**Comment by mindthump** [comment]
Sorry to get back so late on this, the new release works perfectly. Thanks!!

**Comment by zorro3** [comment]
Great, thanks!
