### ISSUE TITLE
support for config directories

### ISSUE THREAD

**Issue by mzagrabe** [bw2/ConfigArgParse#61]
Hello,

Thanks for writing configargparse - it is great.

It would be nice to extend the software to include arbitrary config snippets in a directory without having to specify each snippet file. Perhaps adding a named parameter to the constructor:

default_config_directories = [ '/etc/software/conf-enabled' ]
default_config_directories_globs = [ '*.conf', '*.yaml' ]

or

default config_directories = [
    { 'directory' = '/etc/software/conf-enabled', glob = '*.conf' },
]

Pros and cons to each.

Also, a way to specify the config-directory on the command line:

config_arg_parser.add(
    '--config-directory',
    is_config_directory = True,
    glob = '*.conf',
)

For larger software projects, it is nice to break the configurations into snippets. This would be a very useful feature. It would also allow mimicking a conf-available, conf-enabled paradigm.

Thanks for considering it!

-m

**Comment by bw2** [comment]
Supporting multiple files in a directory does seem useful, but the constructor already has many args, so as a compromise I extended `default_config_files` behavior to support globs:
```
default_config_files = ['/etc/conf/default.conf', '/etc/software/conf-enabled/*.conf', ]
```
