### ISSUE TITLE
bug when setting a float value to -10. and not -10.0

### ISSUE THREAD

**Issue by londumas** [bw2/ConfigArgParse#62]
When fixing a value defined with:
parser.add('--'+par_name,type=types.FloatType,required=False,help=par_help, default=par_default)

I get an error if in the config file i set 
`
par_name = -10.
`
or 
`
par_name = -9.
`
The error doesn't occur in the following:
 `
par_name = -10.0

par_name = 10.

par_name = 10.0
`

**Comment by londumas** [comment]
Tested with ConfigArgParse 0.10.0.

I can test with the latest ConfigArgParse, if you need me to.

**Comment by londumas** [comment]
the error is:
`
fit: error: argument --param_name: expected one argument
`

**Comment by londumas** [comment]
any idea ?

**Comment by bw2** [comment]
argparse behaves the same way. 
```
import argparse as ap
p = ap.ArgumentParser()
p.add_argument("-x", type=float, required=True)
options = p.parse_args()
print(options)
```

```
python test_script.py -x -10.
usage: test_script.py [-h] -x X
test_script.py: error: argument -x: expected one argument
```

Why do you need `-10.` to work?

**Comment by londumas** [comment]
Hi @bw2, thank you for the attention to my bug report.

What I don't like is that in "sys" there are no problems to give "-10.":

`import sys

a = sys.argv[1]

print a

a = float(a)

print a`

`python test_script.py -10.`


Furthermore I see many reasons to give "-10." and not "-10":
    -    -10. and -10 are not the same number one is a real the other a relative integer
    -    even if we cast -10 into a float, it breaks the principle of code self readability.
I want my readers to see that the input should be a float, and so that the parameter is a float.
    -    In physics -10. and -10.0 isn't the same number.
    -    there is a lack of symmetry between 10. working and -10. working.
    -    it works with a basic module as sys

Would you agree ?

**Comment by bw2** [comment]
Technically you are right, there's no reason -10. shouldn't work. 
I you see a straight forward way to fix this, please submit a pull request.

**Comment by londumas** [comment]
Thank you for the answer.

I don't really see a good way to correct it. Have you any idea why this is happening ?

Maybe "expected one argument" says that a "." with no zero after is a delimiter.

**Comment by bw2** [comment]
It looks like the issue is in argparse which has this line:

```
# determines whether an "option" looks like a negative number
self._negative_number_matcher = _re.compile(r'^-\d+$|^-\d*\.\d+$')
```

int the  _ActionsContainer constructor. The fix would be to somehow replace this regexp.

**Comment by londumas** [comment]
So it is a deliberative choice of the argparse team.

It would be good to know why they choose to make this selection before introducing some more
bugs.

Or we can overrite their code line.

**Comment by londumas** [comment]
Anything I can do to make this issue move ?

**Comment by bw2** [comment]
sorry, I will not be able to work on this. If you'd like to submit a pull request, I will take a look.

**Comment by londumas** [comment]
Also configArgParser accepts "1.0e-5  " but doesn't accepts " -1.0e-5 "

The problem is related to formating negative numbers.

**Comment by londumas** [comment]
I found a way to fix it, doing:

p = ap.ArgumentParser()
p._negative_number_matcher = ap._re.compile(r'^-\d+$|^-\d*\.\d+$|^-\d*\.')

p.add_argument("-x", type=float, required=True)
options = p.parse_args()
print(options)

how could we fix that in configArgParser ?
