### ISSUE TITLE
new release soon?

### ISSUE THREAD

**Issue by bcdarwin** [bw2/ConfigArgParse#63]
Some important bugfixes have landed in develop but not made it into a release yet ... wondering if you can make one so that a "good" version can be resolved from PyPI without having to put GitHub URIs into my `setup.py`  .... thanks!

**Comment by josubg** [comment]
Same problem Here

**Comment by bw2** [comment]
Sorry this took me this long to get to. 
I will push the latest changes to pypi tomorrow.
