### ISSUE TITLE
Pypi is not up to date 0.11.0

### ISSUE THREAD

**Issue by flaurencin** [bw2/ConfigArgParse#65]
Hi,

Could you update Pypi, because it would be convinient as I'm using a lot Yaml configuration files?

Kind regards,

**Comment by flaurencin** [comment]
Please it would be so much more convenient :+1:   I have so many scripts using this with yaml, and I would like people to just do pip install.

Thanks a lot.

**Comment by TimZehta** [comment]
This issue duplicates #63

**Comment by bw2** [comment]
Sorry this took me this long to get to. 
I will push the latest changes to pypi tomorrow.

**Comment by flaurencin** [comment]
Thank you So much ;-)
