### ISSUE TITLE
is_write_out_config_file_arg doesn't work with custom types

### ISSUE THREAD

**Issue by jordansamuels** [bw2/ConfigArgParse#69]
I love the ability to memorialize ad hoc options into a config file via is_write_out_config_file_arg.  However, this doesn't work with custom types. Consider the following code:

```
def valid_date(s):
    try:
        return datetime.datetime.strptime(s, "%Y-%m-%d")
    except ValueError:
        raise Exception("Not a valid date: {s}".format(**locals()))

def main():
    p = ArgParser()
    p.add_argument('--config-file', is_config_file_arg=True)
    p.add_argument('--output-config', is_write_out_config_file_arg=True, help='write config file and exit')
    p.add_argument('--date', required=True, type=valid_date)

    print(p.parse_args())
```

If we run via `test.py --date 2016-09-09 --output-config test.ini` then the test.ini will be:

```
output-config = test.ini
date = 2016-09-09 00:00:00
```

But this will not work when we run `test.py --config-file test.ini` because the date value is no longer valid.  We prefer the output to be:

```
output-config = test.ini
date = 2016-09-09
```

I devised a fix for this that involves using original command-line arguments for the values, instead of parsed values.  Let me know if you'd like a pull request.

Thanks,
Jordan

**Comment by bw2** [comment]
It'd be neat if that worked. I'm not sure I understand the fix, but if it passes all tests, and doesn't change the core code that much, it would be good to add it.

**Comment by jordansamuels** [comment]
Done, submitted pull request. Please ignore the earlier commit (c27e558) as it had commented out the test.test_argparse stuff.  0a47f66 is the right one (and the pull request should be for this one).
