### ISSUE TITLE
Saving back the configuration?

### ISSUE THREAD

**Issue by KerstinKeller** [bw2/ConfigArgParse#70]
Hi,

my usecase is that i would like to overwrite my configuration file with the information provided on the command line. Also for me it should be the default behavior, e.g. the user does not have to specify a file for this, but it should be written to the config file that it was read from.

Unfortunately, I can't quite figure out how that can be achieved. Searching through the code, I saw that you can add an argument with `is_write_out_config_file_arg=True`, but then the program will exit.

Is it possible, to dump the configuration to a file such that it can be reread?

```
p = configargparse.getArgumentParser(default_config_files=['./.cfg'])
# General properties
p.add('-c', '--config', is_config_file=True, help='config file path')
p.add_argument("myarg", default="some_str", type=str, help="A random string parameter")
# ....
p.parse_args()

#now dump it - how to?
p.dump_config(p.config)
```

**Comment by bw2** [comment]
This needs some refactoring to extract 
https://github.com/bw2/ConfigArgParse/blob/master/configargparse.py#L560
into a separate method. 
A pull request would be appreciated.
