### ISSUE TITLE
Breaking change for Subparsers

### ISSUE THREAD

**Issue by einsweniger** [bw2/ConfigArgParse#74]
Commit 381a165a098e140247bda8e00a9312def03f4663 breaks subparsers:

Instead of appending config file values, to those already on commandline, it is now the other way round.

Mostly since 

> args += env_var_args

is not the same as

> args = env_var_args + args

When I execute a command that is supposed to use git-like sub-command syntax like:

> $ git status --full

The v0.10 behaviour resulted in:

> args = ['status', '--full', CFG_PARAMS]

v0.11 will now hand this to argparse

> args = [CFG_PARAMS, 'status', '--full']

Argparse will then exit, because the main parser will not accept the parameters and additionaly cannot hand them down to the subparser.

The fix _should_ be as easy as switching from

> args = env_var_args + args

to

> args = args + env_var_args

on several lines in configargparse, but since I don't know if some other things do depend on the new behavior, I should leave this up to you.

**Comment by dansondergaard** [comment]
This issue is pretty severe. Are there any timeline for a 0.12 that fixes this?

**Comment by bw2** [comment]
Should be fixed by 0.12 release
