### ISSUE TITLE
docs should mention that envvars don't support lists yet

### ISSUE THREAD

**Issue by jdelic** [bw2/ConfigArgParse#79]
I just spent about 2 hours debugging and then realized that configargparse [does not support lists in envvars, as noted by a single `TODO`](https://github.com/bw2/ConfigArgParse/blob/9b3244efa26058b2d724794363f2bc2b279aa293/configargparse.py#L467). That's unfortunate and not mentioned anywhere as far as I can tell :).

Actually, parsing envvars for lists would be even better, but I assume it's not easy to do, which is why it hasn't been done yet.

**Comment by bw2** [comment]
Sorry about that. A PR to fix the docs or the code would be appreciated.

**Comment by jobevers** [comment]
Looks like it supports lists now: https://github.com/bw2/ConfigArgParse/blob/c36673f5515bbbc6289eac541b82785b2fc93aa4/configargparse.py#L439 ?

**Comment by bw2** [comment]
Good call, list strings are supported now.
