### ISSUE TITLE
Catching an error caused by a faulty config/settings file

### ISSUE THREAD

**Issue by gamesbook** [bw2/ConfigArgParse#83]
It would be extremely useful if there was a way to trap an error arising from a misconfigured settings file e.g. the parser requires `user` but the file has the setting `username`.

I would like to be able to do this:

```
try:
    parser.parse_args()
except Exception as err:
    logger.error('Unable to load settings:%s' % err)
```

At present, the script just "dies":
```
usage: arg.py [-h] [-s SETTINGS] [-n NAME] [-p PORT] [-o HOST] [-u USER]
arg.py: error: unrecognized arguments: --username derek
```

**Comment by bw2** [comment]
the current behavior is based on the behavior of argparse for unexpected args.
You might want to use `parse_known_args()` instead of `parse_args()`
