### ISSUE TITLE
Allow null values in yaml config file

### ISSUE THREAD

**Issue by kaniblu** [bw2/ConfigArgParse#86]
Allow specifying null values in yaml config file using yaml-like syntax:

    # the following should create arguments of 
    # {"foo": 1234, "bar": None, "joe": 1234}
    foo: 1234
    bar:
    joe: 1234

Currently above config file will produce an error complaining about unexpected end-of-line.

**Comment by bw2** [comment]
Are you using the YAMLConfigFileParser ? if yes, your config file just needs to conform to the syntax expected by PyYAML which is what handles the parsing:
https://github.com/bw2/ConfigArgParse/blob/master/configargparse.py#L220
