### ISSUE TITLE
Add a "dump config" option

### ISSUE THREAD

**Issue by toejough** [bw2/ConfigArgParse#9]
Any "--" argument can be used in a config file, and a user can see what those options are by parsing the help text, but there are other tools (like "clang-format") which will dump the config file equivalent of your command line if you ask them to.  

You can then edit and modify this file as required, but you don't start from scratch, as you currently must do for ConfigArgParse.

If there's a straightforward way to do so outside of the module, that's cool, too, but I dug in a little and didn't see one.

My naive solution was to format the output of "vars(args)", but that fails to cover the cases where a flag is used (but not actually used, so its value is still "False"), or where a value is being stored to a destination different than its CLI name (via the "dest" kwarg), or where the CLI is not a "--" option.

To do this correctly, I really need to get access to the parser internals, so I'm requesting it as a new feature of the module itself.

**Comment by bw2** [comment]
This has been implemented. 
If no further feedback, this issue will be closed as soon as I push v0.9.4 to PyPI.
