### ISSUE TITLE
`key = False` with argument `type=bool` sets `key` to `True`

### ISSUE THREAD

**Issue by yunesj** [bw2/ConfigArgParse#91]
With code: `p.add('--key', type=bool)`
and config: `key = False`
value for `key` is set to `True`.

`action='store_true'` works somewhat as expected.

**Comment by bw2** [comment]
A pull request / fix would be appreciated.

**Comment by bermanmaxim** [comment]
I don't think this is a bug; this is similar to the behavior of `argparse`, since `bool` is not one of the supported types, and `bool("False") == True`.

**Comment by yunesj** [comment]
I agree.
